language: node_js
addons:
  firefox: 'latest'
apt:
  packages:
    - google-chrome-stable
node_js:
  - '8'
  - '9'
  - '10'
cache:
  directories:
    - 'node_modules'

before_script:
  - npm install codacy-coverage
script:
  - npm run test-travis
after_success:
  - cat ./coverage/lcov/lcov.info | codacy-coverage
